### ISSUE TITLE
Sometimes gets stuck in a disconnected state

### ISSUE THREAD

**Issue by dhleong** [dhleong/hangr#28]
Haven't looked too deeply into this as it's not super common; not sure if it's a bug in hangupsjs, our reconnect logic, or what. No consistent repro yet, but I suspect a combination of disabling wifi and putting my laptop to sleep might trigger it.

**Comment by dhleong** [comment]
Occurred just now. Here's some log:

```
Sun Mar 19 2017 21:55:43 GMT-0400 (EDT) setActive(true)
Sun Mar 19 2017 22:13:36 GMT-0400 (EDT) SUSPEND
Sun Mar 19 2017 22:13:37 GMT-0400 (EDT) setActive(false)
Mon Mar 20 2017 00:13:53 GMT-0400 (EDT) conn: failed; reconnecting after 1000
Mon Mar 20 2017 07:11:10 GMT-0400 (EDT) setActive(true)
```

It's not clear whether the `setTimeout` never went through because the system was suspended, or if the `client.connect()` call never finished; adding more logging so hopefully we can pin this down.

**Comment by dhleong** [comment]
This repro'd for me just now. Here's some logs:

```
2017-04-04 23:27:46 INFO poller stopped 400
Tue Apr 04 2017 23:27:46 GMT-0400 (EDT) conn: failed (Error: Bad SID) reconnecting after 1000
Tue Apr 04 2017 23:27:47 GMT-0400 (EDT) conn: Reconnect...
Tue Apr 04 2017 23:27:52 GMT-0400 (EDT) conn: Connected!
Tue Apr 04 2017 23:27:53 GMT-0400 (EDT) setActive(true)
Tue Apr 04 2017 23:31:17 GMT-0400 (EDT) SUSPEND
Tue Apr 04 2017 23:31:18 GMT-0400 (EDT) setActive(false)
2017-04-05 1:31:32 INFO poller stopped ENETDOWN
Wed Apr 05 2017 01:31:32 GMT-0400 (EDT) conn: failed (Error: connect ENETDOWN 209.85.201.189:443 - Local (192.168.1.207:61136)) reconnecting after 1000
Wed Apr 05 2017 01:31:33 GMT-0400 (EDT) conn: Reconnect...
Wed Apr 05 2017 16:08:41 GMT-0400 (EDT) setActive(true)
```

SO... apparently the promise on `client.connect` just never fulfills OR errors?

**Comment by dhleong** [comment]
Here's another example:

```
Sun May 07 2017 11:26:00 GMT-0400 (EDT) setActive(true)
Sun May 07 2017 11:26:01 GMT-0400 (EDT) SUSPEND
Sun May 07 2017 11:26:01 GMT-0400 (EDT) setActive(false)
Sun May 07 2017 13:26:44 GMT-0400 (EDT) conn: failed (Error: Connection timeout) reconnecting after 1000
Sun May 07 2017 13:26:45 GMT-0400 (EDT) conn: Reconnect...
Sun May 07 2017 14:23:59 GMT-0400 (EDT) setActive(true)
```

Perhaps we should just create a new Client each time we need to reconnect....

**Comment by dhleong** [comment]
Got some logs with hangupsjs debugging enabled:

```
2017-05-10 10:23:03 DEBUG emit noop 
2017-05-10 10:23:04 DEBUG request for https://clients6.google.com/chat/v1/clients/setactiveclient result: 200 
Wed May 10 2017 10:23:04 GMT-0400 (EDT) setActive(true)
2017-05-10 10:23:31 DEBUG emit noop 
Wed May 10 2017 10:23:33 GMT-0400 (EDT) SUSPEND
2017-05-10 10:23:33 DEBUG request for https://clients6.google.com/chat/v1/clients/setactiveclient result: 200 
Wed May 10 2017 10:23:33 GMT-0400 (EDT) setActive(false)
2017-05-10 10:23:57 DEBUG emit noop 
2017-05-10 12:24:13 DEBUG activity wait timeout after 45 secs
2017-05-10 12:24:13 DEBUG disconnect
2017-05-10 12:24:13 DEBUG channel stop
2017-05-10 12:24:13 DEBUG PushDataParser reset
2017-05-10 12:24:13 DEBUG emit connect_failed Error: Connection timeout
    at /Users/dhleong/git/hangr/node_modules/hangupsjs/lib/client.js:233:49
    at _fulfilled (/Users/dhleong/git/hangr/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/dhleong/git/hangr/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/dhleong/git/hangr/node_modules/q/q.js:796:13)
    at /Users/dhleong/git/hangr/node_modules/q/q.js:857:14
    at runSingle (/Users/dhleong/git/hangr/node_modules/q/q.js:137:13)
    at flush (/Users/dhleong/git/hangr/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Wed May 10 2017 12:24:13 GMT-0400 (EDT) conn: failed (Error: Connection timeout) reconnecting after 1000
2017-05-10 12:24:13 DEBUG long poll end
Wed May 10 2017 12:24:14 GMT-0400 (EDT) conn: Reconnect...
2017-05-10 12:24:14 DEBUG emit connecting 
2017-05-10 12:24:14 DEBUG getting auth...
2017-05-10 12:24:14 DEBUG using cached cookies
2017-05-10 12:24:14 DEBUG getAuth done
2017-05-10 12:24:14 DEBUG fetching pvt
2017-05-10 12:24:14 DEBUG found pvt token <TOKEN_REDACTED>
2017-05-10 12:47:19 DEBUG request for https://clients6.google.com/chat/v1/clients/setactiveclient result: 200 
Wed May 10 2017 12:47:19 GMT-0400 (EDT) setActive(true)
Request: select /c/<CONV_ID_REDACTED>
Request: focus(<CONV_ID_REDACTED>, true)
2017-05-10 12:47:25 DEBUG request for https://clients6.google.com/chat/v1/conversations/setfocus result: 200 
setFocus(<CONV_ID_REDACTED>, true) OK
```

**Comment by dhleong** [comment]
Didn't realize I already had so many logs for this, but here's another:

```
Fri Oct 06 2017 23:09:54 GMT-0400 (EDT) SUSPEND
Fri Oct 06 2017 23:09:55 GMT-0400 (EDT) setActive(false)
Fri Oct 06 2017 23:10:26 GMT-0400 (EDT) RESUME
Fri Oct 06 2017 23:10:26 GMT-0400 (EDT) setActive(true)
Fri Oct 06 2017 23:10:26 GMT-0400 (EDT) gotEventsSince: {
 "response_header": {
  "status": 1,
  "request_trace_id": "-2678074908367345306",
  "current_server_time": 1507345826109000
 },
 "sync_timestamp": 1507345526211000,
 "conversation_state": []
}
Fri Oct 06 2017 23:11:04 GMT-0400 (EDT) SUSPEND
Fri Oct 06 2017 23:11:04 GMT-0400 (EDT) setActive(false)
Sat Oct 07 2017 01:11:46 GMT-0400 (EDT) conn: failed (Error: Connection timeout) reconnecting after 1000
Sat Oct 07 2017 01:11:47 GMT-0400 (EDT) conn: Reconnect...
Sat Oct 07 2017 08:08:59 GMT-0400 (EDT) setActive(true)
```

A couple things we can notice here:

1. Client encounters "connection timeout" while *suspended*, and still tries to reconnect. 
1. For whatever reason, that reconnect neither fails nor succeeds.
1. We never get a `RESUME` event, just `setActive(true)`.

Looking at the code, the "connection failed" event actually disables power monitoring, which makes sense; it's not the job of the power monitoring to reconnect. 

4. `setActive(true)` is actually only logged *after the request completes*. The request actually goes out *and completes successfully* even though we don't have an active connection. 

This is because `setActive()` just checks for the existence of the `client` object, and NOT the `.connected` state. Note that the "connection timeout" event does *not* delete the `client` object (we use it in `_reconnect`) and it also doesn't update `.connected` (it should).

5. As noted above, `setTimeout` does work while suspended, since we get "conn: Reconnect..." logged. 

Let's go down the rabbit hole a bit, analyzing the debug logs in the above comment:

- We see that it does successfully find the `pvt token`, so it *must* get to `initChat`. 
- Presumably, network requests via the `req()` function *work* (IE: don't silently die) or else the request to fetch the pvt token would not happen. We also don't see "init failed" logged, so it must fetch the chat init successfully
- We never see any logs about "init data." While it could be that there just isn't any, presumably there always is. This suggests to me that something is going wrong in the `eval()` step, since something else should throw an error....
