### ISSUE TITLE
Repeated Oauth window spawns on OSX 10.9

### ISSUE THREAD

**Issue by krackers** [dhleong/hangr#29]
When trying to launch the app and login for the first time, the app keeps continually spawning oauth windows (like 1 every second). Platform is osx 10.9 (which might be the cause of some issues as many new nswindow apis were added in 10.10+) .

Here's the terminal output (which keeps repeating the same errors as long as it keeps running).
```

/Applications/hangr.app/Contents/MacOS/hangr ; exit;
2017-03-13 14:38:00.823 hangr[411:507] Bartender: Loaded BartenderHelperNinetySix
login: auth result
login: no oauth token
2017-03-13 14:38:00 ERROR getAuth failed No oauth token
Mon Mar 13 2017 14:38:00 GMT-0700 (PDT) conn: failed; reconnecting after 1000
conn: ERROR! { '0': 
   TypeError: Cannot read property 'send' of undefined
       at _allOpenWindows.forEach.win (/Applications/hangr.app/Contents/Resources/app/docked-window.js:73:13)
       at Array.forEach (native)
       at DockManager.dispatch (/Applications/hangr.app/Contents/Resources/app/docked-window.js:72:32)
       at ConnectionManager.<anonymous> (/Applications/hangr.app/Contents/Resources/app/connection.js:293:16)
       at emitOne (events.js:96:13)
       at ConnectionManager.emit (events.js:188:7)
       at Client.client.on (/Applications/hangr.app/Contents/Resources/app/connection.js:216:18)
       at emitOne (events.js:96:13)
       at Client.emit (events.js:188:7)
       at Client.module.exports.Client.emit (/Applications/hangr.app/Contents/Resources/app/node_modules/hangupsjs/lib/client.js:218:36) }
login: auth result
login: no oauth token
2017-03-13 14:38:02 ERROR getAuth failed No oauth token
Mon Mar 13 2017 14:38:02 GMT-0700 (PDT) conn: failed; reconnecting after 1000
conn: ERROR! { '0': 
   TypeError: Cannot read property 'send' of undefined
       at _allOpenWindows.forEach.win (/Applications/hangr.app/Contents/Resources/app/docked-window.js:73:13)
       at Array.forEach (native)
       at DockManager.dispatch (/Applications/hangr.app/Contents/Resources/app/docked-window.js:72:32)
       at ConnectionManager.<anonymous> (/Applications/hangr.app/Contents/Resources/app/connection.js:293:16)
       at emitOne (events.js:96:13)
       at ConnectionManager.emit (events.js:188:7)
       at Client.client.on (/Applications/hangr.app/Contents/Resources/app/connection.js:216:18)
       at emitOne (events.js:96:13)
       at Client.emit (events.js:188:7)
       at Client.module.exports.Client.emit (/Applications/hangr.app/Contents/Resources/app/node_modules/hangupsjs/lib/client.js:218:36) }
login: auth result
login: no oauth token
2017-03-13 14:38:03 ERROR getAuth failed No oauth token
Mon Mar 13 2017 14:38:03 GMT-0700 (PDT) conn: failed; reconnecting after 1000
conn: ERROR! { '0': 
   TypeError: Cannot read property 'send' of undefined
       at _allOpenWindows.forEach.win (/Applications/hangr.app/Contents/Resources/app/docked-window.js:73:13)
       at Array.forEach (native)
       at DockManager.dispatch (/Applications/hangr.app/Contents/Resources/app/docked-window.js:72:32)
       at ConnectionManager.<anonymous> (/Applications/hangr.app/Contents/Resources/app/connection.js:293:16)
       at emitOne (events.js:96:13)
       at ConnectionManager.emit (events.js:188:7)
       at Client.client.on (/Applications/hangr.app/Contents/Resources/app/connection.js:216:18)
       at emitOne (events.js:96:13)
       at Client.emit (events.js:188:7)
       at Client.module.exports.Client.emit (/Applications/hangr.app/Contents/Resources/app/node_modules/hangupsjs/lib/client.js:218:36) }
login: auth result
login: no oauth token
2017-03-13 14:38:05 ERROR getAuth failed No oauth token
Mon Mar 13 2017 14:38:05 GMT-0700 (PDT) conn: failed; reconnecting after 1000
conn: ERROR! { '0': 
   TypeError: Cannot read property 'send' of undefined
       at _allOpenWindows.forEach.win (/Applications/hangr.app/Contents/Resources/app/docked-window.js:73:13)
       at Array.forEach (native)
       at DockManager.dispatch (/Applications/hangr.app/Contents/Resources/app/docked-window.js:72:32)
       at ConnectionManager.<anonymous> (/Applications/hangr.app/Contents/Resources/app/connection.js:293:16)
       at emitOne (events.js:96:13)
       at ConnectionManager.emit (events.js:188:7)
       at Client.client.on (/Applications/hangr.app/Contents/Resources/app/connection.js:216:18)
       at emitOne (events.js:96:13)
       at Client.emit (events.js:188:7)
       at Client.module.exports.Client.emit (/Applications/hangr.app/Contents/Resources/app/node_modules/hangupsjs/lib/client.js:218:36) }
login: auth result
login: no oauth token
2017-03-13 14:38:06 ERROR getAuth failed No oauth token
Mon Mar 13 2017 14:38:06 GMT-0700 (PDT) conn: failed; reconnecting after 1000
conn: ERROR! { '0': 
   TypeError: Cannot read property 'send' of undefined
       at _allOpenWindows.forEach.win (/Applications/hangr.app/Contents/Resources/app/docked-window.js:73:13)
       at Array.forEach (native)
       at DockManager.dispatch (/Applications/hangr.app/Contents/Resources/app/docked-window.js:72:32)
       at ConnectionManager.<anonymous> (/Applications/hangr.app/Contents/Resources/app/connection.js:293:16)
       at emitOne (events.js:96:13)
       at ConnectionManager.emit (events.js:188:7)
       at Client.client.on (/Applications/hangr.app/Contents/Resources/app/connection.js:216:18)
       at emitOne (events.js:96:13)
       at Client.emit (events.js:188:7)
       at Client.module.exports.Client.emit (/Applications/hangr.app/Contents/Resources/app/node_modules/hangupsjs/lib/client.js:218:36) }
login: auth result
login: no oauth token
2017-03-13 14:38:08 ERROR getAuth failed No oauth token
Mon Mar 13 2017 14:38:08 GMT-0700 (PDT) conn: failed; reconnecting after 1000
conn: ERROR! { '0': 
   TypeError: Cannot read property 'send' of undefined
       at _allOpenWindows.forEach.win (/Applications/hangr.app/Contents/Resources/app/docked-window.js:73:13)
       at Array.forEach (native)
       at DockManager.dispatch (/Applications/hangr.app/Contents/Resources/app/docked-window.js:72:32)
       at ConnectionManager.<anonymous> (/Applications/hangr.app/Contents/Resources/app/connection.js:293:16)
       at emitOne (events.js:96:13)
       at ConnectionManager.emit (events.js:188:7)
       at Client.client.on (/Applications/hangr.app/Contents/Resources/app/connection.js:216:18)
       at emitOne (events.js:96:13)
       at Client.emit (events.js:188:7)
       at Client.module.exports.Client.emit (/Applications/hangr.app/Contents/Resources/app/node_modules/hangupsjs/lib/client.js:218:36) }
Killed: 9
logout


```

**Comment by krackers** [comment]
Ok so after just being really quick and copy pasting my email address before the next window spawned, I was able to enter my password and get it working. Everything else works fine now.

**Comment by dhleong** [comment]
Thanks for the report! Uploading 0.1.1-alpha now that should fix the issue.
